# Generated by Django 2.1.5 on 2013-01-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared',
            old_name='user',
            new_name='recevier',
        ),
        migrations.AddField(
            model_name='shared',
            name='sender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
